# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the script into the container at /app
COPY python_finance_3.py /app/

# Install any dependencies your script might need
RUN pip install yfinance matplotlib

# Command to run your script when the container starts
CMD ["python", "python_finance_3.py"]
